project:
  type: website

website:
  title: "♪ Song Popularity ♪"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - overview.qmd
      - comparisons.qmd
      - observations.qmd

    right:
      - sources.qmd
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



