---
title: "Other Observations"
execute: 
  echo: false
---
```{r}
#| warning: false
library(tidyverse)
```

## Loudness & Energy
```{r}
#| warning: false

song_data <- read.csv("song_data.csv")

loudness <- "loudness"  
energy <- "energy"  

song_data <- song_data %>%
  select(all_of(c(loudness, energy))) %>%
  na.omit()

ggplot(song_data, aes_string(x = loudness, y = energy)) +
  geom_point(alpha = 0.5, color = "#c09567") +
  geom_smooth(method = "loess", se = FALSE, color = "forestgreen")
  ggtitle(paste("Comparison between", loudness, "and", energy)) +
  theme_minimal() + 
  theme(                             
   plot.title = element_text(size = 16, face = "bold", hjust = 0.5), 
   axis.title = element_text(size = 14, face = "bold"),               
   axis.text = element_text(size = 11)                              
  )
```
## Danceability
```{r}
#| warning: false
song_data <- read.csv("song_data.csv")

danceability_column <- "danceability"

song_data <- song_data %>%
  select(all_of(danceability_column)) %>%
  na.omit()

ggplot(song_data, aes_string(x = danceability_column)) +
  geom_density(color = "pink", size = 2) +
  ggtitle("Density Plot of Song Danceability") +
  xlab("Song Danceability") +
  theme_minimal() + 
  theme(                             
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5), 
    axis.title = element_text(size = 14, face = "bold"),               
    axis.text = element_text(size = 11)                              
  )
```

