---
title: "Overview"
execute:
  echo: false
---
```{r}
#| warning: false
library(tidyverse)
```

## Keys

The general twelve musical keys have varying levels of frequency; D# is the lowest.

```{r}
#| warning: false
song_data <- read.csv("song_data.csv")

key_column <- "key"

song_data <- song_data %>%
  select(all_of(key_column)) %>%
  na.omit()

key_labels <- c("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")
song_data[[key_column]] <- factor(song_data[[key_column]], levels = 0:11, labels = key_labels)

key_frequency <- table(song_data[[key_column]])
key_frequency_df <- as.data.frame(key_frequency)
colnames(key_frequency_df) <- c("Key", "Frequency")

ggplot(key_frequency_df, aes(x = Key, y = Frequency)) +
  geom_bar(stat = "identity", fill = "#c09567") +
  ggtitle("Frequency of Each Key in the Dataset") +
  xlab("Key") +
  ylab("Frequency") +
  theme_minimal() + 
  theme(                             
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5), 
    axis.title = element_text(size = 14, face = "bold"),               
    axis.text = element_text(size = 11)                              
  )

```

## Acousticness

Acousticness is a confidence measure of whether the song uses acoustic instruments (like a guitar) as opposed to electric instruments.

```{r}
#| warning: false
song_data <- read.csv("song_data.csv")

popularity_column <- "song_popularity"
acousticness_column <- "acousticness"

song_data <- song_data %>%
  select(all_of(c(popularity_column, acousticness_column))) %>%
  na.omit()

ggplot(song_data, aes(acousticness)) +
  geom_histogram(binwidth = 0.05, fill = "pink", color = "white") +
  ggtitle("Distribution of Acousticness") +
  xlab("Acousticness") +
  ylab("Frequency") +
  theme_minimal() + 
  theme(                             
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5), 
    axis.title = element_text(size = 14, face = "bold"),               
    axis.text = element_text(size = 11)                              
  )

```